server: 
  port: 8080
eureka:
  client:
    service-url:
     defaultZone: http://localhost:8761/eureka/
spring:
 application:
  name: APIGateWayService
 cloud:
    gateway:
      routes:
      - id: EmployeeService
        uri: http://localhost:8088/
        predicates:
        - Path=/dispEmployee/**
      - id: EmployeeService
        uri: http://localhost:8088/
        predicates:
        - Path=/getEmployee/{empID}/**
      - id: EmployeeService
        uri: http://localhost:8088/
        predicates:
        - Path=/createEmployee/**
      - id: EmployeeService
        uri: http://localhost:8088/
        predicates:
        - Path=/updateEmployee/{empID}/**
      - id: EmployeeService
        uri: http://localhost:8088/
        predicates:
        - Path=/deleteEmployee/{empID}/**
      - id: AssessmentService
        uri: http://localhost:8084/
        predicates:
        - Path=/dispAssessment/**
      - id: AssessmentService
        uri: http://localhost:8084/
        predicates:
        - Path=/getAssessment/{empID}/**
      - id: AssessmentService
        uri: http://localhost:8084/
        predicates:
        - Path=/createAssessment/**
      - id: AssessmentService
        uri: http://localhost:8084/
        predicates:
        - Path=/updateAssessment/{empID}/**
      - id: AssessmentService
        uri: http://localhost:8084/
        predicates:
        - Path=/deleteAssessment/{empID}/**
      - id: CertificationService
        uri: http://localhost:8086/
        predicates:
        - Path=/dispCertification/**
      - id: CertificationService
        uri: http://localhost:8086/
        predicates:
        - Path=/getCertification/{empID}/** 
      - id: CertificationService
        uri: http://localhost:8086/
        predicates:
        - Path=/createCertification/**
      - id: CertificationService
        uri: http://localhost:8086/
        predicates:
        - Path=/updateCertification/{empID}/** 
      - id: CertificationService
        uri: http://localhost:8086/
        predicates:
        - Path=/deleteCertification/{empID}/** 
      - id: CaseStudyService
        uri: http://localhost:8087/
        predicates:
        - Path=/dispCaseStudy/**
      - id: CaseStudyService
        uri: http://localhost:8087/
        predicates:
        - Path=/getCaseStudy/{empID}/**
      - id: CaseStudyService
        uri: http://localhost:8087/
        predicates:
        - Path=/createCaseStudy/**
      - id: CaseStudyService
        uri: http://localhost:8087/
        predicates:
        - Path=/updateCaseStudy/{empID}/**
      - id: CaseStudyService
        uri: http://localhost:8087/
        predicates:
        - Path=/deleteCaseStudy/{empID}/**
      - id: LoginService
        uri: http://localhost:8075/
        predicates:
        - Path=/api/jwt/**
      - id: ProjectService
        uri: http://localhost:8085/
        predicates:
        - Path=/dispProject/**
      - id: ProjectService
        uri: http://localhost:8085/
        predicates:
        - Path=/getProject/{empID}/**
      - id: ProjectService
        uri: http://localhost:8085/
        predicates:
        - Path=/createProject/**
      - id: ProjectService
        uri: http://localhost:8085/
        predicates:
        - Path=/updateProject/{empID}/**
      - id: ProjectService
        uri: http://localhost:8085/
        predicates:
        - Path=/deleteProject/{empID}/**
        
        
        
        
        
      