jwt:
  secret: secrectkey123

server:
    port: 8075        
    
    
spring:
    application:
           name: AppsNa_BULT_App_JWTService
    data:
       mongodb:
        uri: mongodb+srv://vk-7397:Kamthan7397@cluster0.b1m6h.mongodb.net/Employees?retryWrites=true&w=majority
eureka:
     client:
          service-url:
                   defaultZone: http://localhost:8761/eureka/          
                          
logging:
  file: 
    path: /my-logs/app.log
    name: log.txt  
    
data:
   exception:
          incmsg: Invalid Credentials!!
            